all: main
CC = gcc

main: src/main.c src/pc.c
	$(CC) -Wall -o $@.exe $^

pc1: src/pc1.c
	$(CC) -Wall -o $@.exe $^

pc2: src/pc2.c
	$(CC) -Wall -o $@.exe $^
	
pc3: src/pc3.c
	$(CC) -Wall -o $@.exe $^
	


	





	




